CREATURE_RATE: 0.1
CSV: False
CSV_NAME_CREATURES: ./logs/creatures.csv
CSV_NAME_GENERAL: ./logs/general.csv
COSTS_PER_MOVE : 0.05
DAYS: 400
DEATH_PROB: 0.0
GHOST_ZONE: 10
GRID_SIZE: 50
GROW_FOOD_RATE: 0.0025
INIT_FOOD_RATE: 0.1
MAX_ENERGY: 10
PF_SIZE: false
PLOT: true
SPEED: true
SUBFRAMES: 1
TO_ENEMIES: false
TO_FRIENDS: false
VIDEO: false
VIDEO_NAME: ./ani.mp4
