# Grid params
GRID_SIZE : 50
CREATURE_RATE : 0.1
INIT_FOOD_RATE : 0.1
GROW_FOOD_RATE : 0.0025
GHOST_ZONE : 10
# Anim Params
DAYS : 400
SUBFRAMES : 1
# Creature params
DEATH_PROB : 0.01
MAX_ENERGY : 10
# Genome params
SPEED : True
TO_FRIENDS : False
TO_ENEMIES : False
PF_SIZE : False
# Ouput params
PLOT : True
VIDEO : False
CSV : True
CSV_NAME_CREATURES : './logs/creatures.csv'
CSV_NAME_GENERAL : './logs/general.csv'
VIDEO_NAME : './ani.mp4'